Hb user wed
fyarkiy/cinema pull request #3
Opened 2020-10-07 16:33 UTC by fyarkiy

2020-10-07 17:50 UTC, Nokafan commented on src/main/java/com/cinema/exception/PasswordEncryptionException.java
> +    public PasswordEncryptionException(String message, Throwable ex) {
Throwable - is it correct?

2020-10-07 17:50 UTC, Nokafan commented on src/main/java/com/cinema/security/AuthenticationServiceImpl.java
> +        return userService.add(user);
We have to salt and hash password in UserServiceImpl

2020-10-07 18:06 UTC, DariiaPikul requested changes

2020-10-07 18:06 UTC, DariiaPikul commented on src/main/java/com/cinema/exception/PasswordEncryptionException.java
> +    public PasswordEncryptionException(String message, Throwable ex) {
Let's change this

2020-10-07 18:06 UTC, DariiaPikul commented on src/main/java/com/cinema/service/impl/UserServiceImpl.java
> +        return userDao.add(user);
All the business logic somehow related to initializing or setting the values to our fields must be on the service layer.
If somebody creates the object _User_ not throughout the _register_ method but using the _userService.create()_ instead, we'll not have its password hashed, which might cause some mistakes in the future while working with the object or with the security itself.
So let's move the hashing logic to this method.

2020-10-07 18:34 UTC, fyarkiy commented on src/main/java/com/cinema/exception/PasswordEncryptionException.java
> +    public PasswordEncryptionException(String message, Throwable ex) {
Any ideas - change to what?

2020-10-07 19:19 UTC, DariiaPikul commented on src/main/java/com/cinema/exception/PasswordEncryptionException.java
> +    public PasswordEncryptionException(String message, Throwable ex) {
Sorry, it's okay :D
Got confused

2020-10-07 19:20 UTC, DariiaPikul approved these changes

2020-10-08 07:51 UTC, RomanDubovskyi commented on src/main/java/com/cinema/service/impl/UserServiceImpl.java
> +        user.setPassword(HashUtil.hashPassword(user.getPassword(),salt));
```suggestion
        user.setSalt(HashUtil.getSalt());
        user.setPassword(HashUtil.hashPassword(user.getPassword(), user.getSalt());
```

2020-10-08 07:51 UTC, RomanDubovskyi commented on src/main/java/com/cinema/dao/impl/UserDaoImpl.java
> +            throw new DataProcessingException("can't find user with email " + email, e);
```suggestion
            throw new DataProcessingException("Exception while getting user with email " + email, e);
```

2020-10-08 09:57 UTC, RomanDubovskyi approved these changes

2020-10-08 11:00 UTC, merged